# Generated by Django 6.0.5 on 2026-07-04 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('coach_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('STARTER', 'Starter 6-9'), ('JUNIOR', 'Junior 10-13'), ('UPPER', 'Upper 14-17')], default='STARTER', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PLAYED', 'Played')], default='SCHEDULED', max_length=20)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='league.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('position', models.CharField(choices=[('PITCHER', 'Pitcher'), ('CATCHER', 'Catcher'), ('FIRST BASE', 'First Base'), ('SECOND BASE', 'Second Base'), ('THIRD BASE', 'Third Base'), ('SHORTSTOP', 'Shortstop'), ('LEFT FIELD', 'Left Field'), ('CENTER FIELD', 'Center Field'), ('RIGHT FIELD', 'Right Field')], max_length=50)),
                ('birth_date', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
            options={
                'unique_together': {('team', 'number')},
            },
        ),
    ]
